"""ARCH43-S1:cases-vocabulary. Mirrors the migration's CHECKs."""

from __future__ import annotations

from typing import Final

TEMPLATE_DRAFT: Final = "DRAFT"
TEMPLATE_PUBLISHED: Final = "PUBLISHED"
TEMPLATE_RETIRED: Final = "RETIRED"
ASSEMBLY_ENTITY: Final = "ENTITY"
ASSEMBLY_BATCH: Final = "BATCH"
ASSEMBLY_MANUAL: Final = "MANUAL"
ASSEMBLY_KEYS: Final = (ASSEMBLY_ENTITY, ASSEMBLY_BATCH, ASSEMBLY_MANUAL)
ENTITY_KINDS: Final = ("PERSON", "ORGANIZATION", "ADDRESS", "ACCOUNT", "ASSET", "SHIPMENT")
CASE_INCOMPLETE: Final = "INCOMPLETE"
CASE_INCONSISTENT: Final = "INCONSISTENT"
CASE_COMPLETE: Final = "COMPLETE"
CASE_CLOSED: Final = "CLOSED"
CASE_STATUSES: Final = (CASE_INCOMPLETE, CASE_INCONSISTENT, CASE_COMPLETE, CASE_CLOSED)
SOURCE_AUTO: Final = "AUTO"
SOURCE_MANUAL: Final = "MANUAL"
SOURCE_REQUEST: Final = "REQUEST"
REQUEST_OPEN: Final = "OPEN"
REQUEST_FULFILLED: Final = "FULFILLED"
REQUEST_EXPIRED: Final = "EXPIRED"
REQUEST_REVOKED: Final = "REVOKED"
JOB_ASSEMBLE: Final = "cases.assemble_document"
EVENT_PACKET_SPLIT: Final = "trigger.packet.split"
EVENT_CASE_COMPLETED: Final = "trigger.case.completed"
EVENT_CASE_INCONSISTENT: Final = "trigger.case.inconsistent"
MAX_REQUIRED: Final = 40
MAX_RULES: Final = 60
