# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path pathnames to be prepended to sys.path after in-place imports
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters for "slug" (default 40)
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow the creation of empty migrations
# write_empty = false

# database connection URL
sqlalchemy.url = driver://placeholder


[post_write_hooks]
# post_write_hooks defines scripts or code executed after a migration
# is written. Example: running black formatters.
# console_scripts = black -l 79 REVISION_SCRIPT_FILENAME


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S