#!/usr/bin/env python
"""ARCH-11 Step 1 — scaffold a golden set from the real corpus.

    python scripts/build_golden_scaffold.py --out evaluation/golden/arch11_golden_v1.draft.json
    python scripts/build_golden_scaffold.py --workspace <uuid> --workspace <uuid>

This does **not** produce a golden set. It produces the paperwork around one:
the workspace and document blocks filled in from the database, and one stub
question per candidate passage with the passage already quoted as a candidate
answer span. A human then writes the questions, deletes the passages that are
not worth asking about, and marks the forbidden documents.

Two reasons it works this way rather than generating questions with an LLM.

**Ground truth generated by the system under test is not ground truth.** If the
same embedding stack that will be measured also chooses which passages are
findable, the golden set encodes the current retrieval's blind spots as the
definition of correct, and the Step 6 gate can never detect them.

**The spans have to be verbatim.** A span is matched by substring against
retrieved chunk text. A paraphrase — which is what a generative pass produces —
matches nothing, and the whole set silently scores zero. So the candidates here
are literal slices of `work_items.extracted_text`, taken at paragraph
boundaries, and the human's job is selection rather than transcription.

Aim for 40-60 questions across at least three documents in at least two
workspaces, with a deliberate spread: a few keyword lookups, a few natural
questions, a few that need a specific number or name, and — this is the one
people leave out — several whose answer is in the *middle* of a long document
rather than on page one.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import uuid
from pathlib import Path
from typing import Any, Optional

# Enforce UTF-8 output streams across Windows CP1252 / Linux
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from sqlalchemy import select  # noqa: E402

from app.db.session import SessionLocal  # noqa: E402
from app.evaluation.golden_set import SCHEMA_VERSION, normalize  # noqa: E402
from app.models.work_item import WorkItem  # noqa: E402
from app.models.workspace import Workspace  # noqa: E402

MIN_SPAN_CHARS = 60
MAX_SPAN_CHARS = 240
_PARAGRAPH = re.compile(r"\n\s*\n")


def _slug(value: str, fallback: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "_", (value or "").lower()).strip("_")
    return cleaned[:40] or fallback


def _candidate_spans(text: str, *, limit: int) -> list[str]:
    """Paragraph-boundary slices long enough to be discriminating.

    Trimmed to `MAX_SPAN_CHARS` at a word boundary, because a span that spills
    across a chunk boundary can never be matched by any single chunk and would
    look like a retrieval failure for the rest of the phase.
    """
    spans: list[str] = []
    seen: set[str] = set()
    for paragraph in _PARAGRAPH.split(text or ""):
        candidate = re.sub(r"\s+", " ", paragraph).strip()
        if len(candidate) < MIN_SPAN_CHARS:
            continue
        if len(candidate) > MAX_SPAN_CHARS:
            candidate = candidate[:MAX_SPAN_CHARS].rsplit(" ", 1)[0]
        key = normalize(candidate)
        if key in seen:
            continue
        seen.add(key)
        spans.append(candidate)
        if len(spans) >= limit:
            break
    return spans


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace",
        action="append",
        default=[],
        help="Workspace UUID. Repeat. Omit to auto-select the two with the "
        "most extracted documents.",
    )
    parser.add_argument("--documents-per-workspace", type=int, default=3)
    parser.add_argument("--spans-per-document", type=int, default=10)
    parser.add_argument(
        "--out", default="evaluation/golden/arch11_golden_v1.draft.json"
    )
    args = parser.parse_args()

    with SessionLocal() as db:
        if args.workspace:
            workspace_ids = [uuid.UUID(value) for value in args.workspace]
        else:
            rows = db.execute(
                select(WorkItem.workspace_id)
                .where(WorkItem.extracted_text.isnot(None))
                .group_by(WorkItem.workspace_id)
            ).scalars().all()
            counts: list[tuple[uuid.UUID, int]] = []
            for workspace_id in rows:
                count = len(
                    db.execute(
                        select(WorkItem.id).where(
                            WorkItem.workspace_id == workspace_id,
                            WorkItem.extracted_text.isnot(None),
                        )
                    ).scalars().all()
                )
                counts.append((workspace_id, count))
            counts.sort(key=lambda pair: pair[1], reverse=True)
            workspace_ids = [pair[0] for pair in counts[:2]]

        if len(workspace_ids) < 2:
            print(
                "[FAIL] fewer than two workspaces hold extracted documents. The "
                "golden set needs at least two so cross-tenant contamination is "
                "measurable at all.",
                file=sys.stderr,
            )
            return 2

        workspaces: list[dict[str, Any]] = []
        documents: list[dict[str, Any]] = []
        questions: list[dict[str, Any]] = []
        question_number = 1

        for position, workspace_id in enumerate(workspace_ids):
            workspace = db.get(Workspace, workspace_id)
            if workspace is None:
                print(f"[FAIL] workspace {workspace_id} not found", file=sys.stderr)
                return 2
            alias = _slug(workspace.slug, f"ws_{position + 1}")
            workspaces.append(
                {
                    "alias": alias,
                    "workspace_id": str(workspace.id),
                    "organization_id": str(workspace.organization_id),
                    "label": workspace.workspace_name,
                }
            )

            items = (
                db.execute(
                    select(WorkItem)
                    .where(
                        WorkItem.workspace_id == workspace_id,
                        WorkItem.extracted_text.isnot(None),
                    )
                    .order_by(WorkItem.created_at.desc())
                    .limit(args.documents_per_workspace)
                )
                .scalars()
                .all()
            )

            for index, item in enumerate(items, start=1):
                text = item.extracted_text or ""
                document_alias = _slug(
                    Path(item.original_filename).stem, f"{alias}_doc{index}"
                )
                documents.append(
                    {
                        "alias": document_alias,
                        "workspace_alias": alias,
                        "work_item_id": str(item.id),
                        "original_filename": item.original_filename,
                        "page_count": item.page_count,
                        "extracted_text_sha256": hashlib.sha256(
                            text.encode("utf-8")
                        ).hexdigest(),
                    }
                )

                for span in _candidate_spans(text, limit=args.spans_per_document):
                    questions.append(
                        {
                            "id": f"q{question_number:03d}",
                            "workspace_alias": alias,
                            "query": "TODO — write the question this passage answers",
                            "answer_spans": [span],
                            "relevant_document_aliases": [document_alias],
                            "forbidden_document_aliases": [],
                            "intent": "TODO",
                            "category": "TODO",
                            "difficulty": "medium",
                            "observed_chunk_ids": [],
                            "notes": "SCAFFOLD — delete this entry or finish it.",
                        }
                    )
                    question_number += 1

    payload = {
        "version": SCHEMA_VERSION,
        "notes": (
            "DRAFT. Every question with a TODO must be written or deleted "
            "before this file is renamed to arch11_golden_v1.json. Target "
            "40-60 finished questions."
        ),
        "workspaces": workspaces,
        "documents": documents,
        "questions": questions,
    }

    target = REPO_ROOT / args.out
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"[INFO] wrote {target}")
    print(
        f"[INFO] {len(workspaces)} workspaces, {len(documents)} documents, "
        f"{len(questions)} candidate questions"
    )
    print(
        "[INFO] next: write the queries, prune to 40-60, then\n"
        "       python -c \"from app.evaluation.golden_set import load_golden_set as l; "
        "l('evaluation/golden/arch11_golden_v1.json')\""
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())