"""Model/migration drift gate with a recorded baseline of known drift.

WHY THIS EXISTS

CI used to run `alembic revision --autogenerate --rev-id ci_drift_probe` and
grep `alembic/versions/ci_drift_probe.py`. alembic.ini's file_template names
the probe `<rev>_<slug>.py`, i.e. `ci_drift_probe_ci_drift_probe.py`, so the
grep never found the file and the gate printed "No drift." on every run. The
first honest run (hardening Phase 1, FINDINGS F-017) found 314 operations:
mostly indexes and constraints that migrations created but the ORM models do
not declare, plus a handful of real column/type mismatches.

WHAT IT CHECKS

Every operation autogenerate proposes is rendered to one canonical line and
compared with alembic/drift_baseline.txt. The gate fails when:

  * an operation is not in the baseline   -> new drift; fix the model or
                                             write the migration
  * a baseline line no longer drifts      -> it was fixed; delete the line so
                                             the drift cannot come back

So the baseline can only shrink. Zero drift is reached when the file is empty.

USAGE (from backend/, database already at head)

    python scripts/check_migration_drift.py
    python scripts/check_migration_drift.py --write-baseline   # rewrite the file
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
VERSIONS_DIR = BACKEND_DIR / "alembic" / "versions"
BASELINE = BACKEND_DIR / "alembic" / "drift_baseline.txt"
PROBE_REV = "ci_drift_probe"
_OP_NAME = re.compile(r"^(create|drop|add|alter|rename)_")


def _generate_probe() -> Path:
    for stale in VERSIONS_DIR.glob(f"{PROBE_REV}*.py"):
        stale.unlink()
    subprocess.run(
        [
            sys.executable, "-m", "alembic", "revision", "--autogenerate",
            "-m", "ci-drift-probe", "--rev-id", PROBE_REV,
        ],
        cwd=BACKEND_DIR,
        check=True,
    )
    probes = list(VERSIONS_DIR.glob(f"{PROBE_REV}*.py"))
    if len(probes) != 1:
        raise SystemExit(f"Expected one probe file for {PROBE_REV}, found {probes}.")
    return probes[0]


def _operations(probe: Path) -> list[str]:
    tree = ast.parse(probe.read_text(encoding="utf-8"))
    upgrade = next(
        node for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == "upgrade"
    )
    found = []
    for node in ast.walk(upgrade):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and isinstance(node.func.value, ast.Name)
            and _OP_NAME.match(node.func.attr)
        ):
            found.append(ast.unparse(node))
    return sorted(set(found))


def _read_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    lines = BASELINE.read_text(encoding="utf-8").splitlines()
    return {line for line in lines if line.strip() and not line.startswith("#")}


def _write_baseline(ops: list[str]) -> None:
    header = (
        "# Known model/migration drift. One autogenerate operation per line.\n"
        "# Generated by scripts/check_migration_drift.py --write-baseline.\n"
        "# Delete lines as the drift is fixed; never add lines by hand. See\n"
        "# docs/hardening/FINDINGS.md F-017.\n"
    )
    BASELINE.write_text(header + "".join(f"{op}\n" for op in ops), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write-baseline", action="store_true")
    args = parser.parse_args()

    probe = _generate_probe()
    try:
        current = _operations(probe)
    finally:
        probe.unlink()

    if args.write_baseline:
        _write_baseline(current)
        print(f"Wrote {len(current)} operation(s) to {BASELINE.relative_to(BACKEND_DIR)}.")
        return 0

    baseline = _read_baseline()
    new = [op for op in current if op not in baseline]
    fixed = sorted(baseline - set(current))

    for op in new:
        print(f"::error::New model/migration drift: {op}")
    for op in fixed:
        print(f"::error::No longer drifts, delete it from drift_baseline.txt: {op}")
    if new or fixed:
        print(f"{len(new)} new, {len(fixed)} fixed-but-still-listed.")
        return 1

    print(f"No new drift. {len(baseline)} known operation(s) remain in the baseline.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
