#!/usr/bin/env python3
"""ARCH43-S1:fit — fit the packet-boundary logistic model with scikit-learn.

    python scripts/fit_packet_boundaries.py            # fit and report; write nothing
    python scripts/fit_packet_boundaries.py --write    # rewrite the fitted block in model.py

Deterministic: fixed training seeds (synthetic.TRAIN_SEEDS) and liblinear.
verify_arch43 T4 calls fit() and compares with the shipped coefficients.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

MODEL_FILE = BACKEND / "app" / "services" / "packets" / "model.py"
VERSION = "pb-1"


def training_rows(seeds):
    from app.services.packets import features as ft
    from app.services.packets import synthetic

    X, y = [], []
    for texts, truth in synthetic.corpus(seeds):
        facts, pair = ft.packet_features(texts)
        for i in range(1, len(texts)):
            if facts[i].blank or facts[i].separator:
                continue  # the planner never starts a document there; do not teach it to
            X.append(ft.vector(pair[i]))
            y.append(1 if (i + 1) in truth else 0)
    return X, y


def fit(seeds=None) -> dict:
    from sklearn.linear_model import LogisticRegression

    from app.services.packets import features as ft
    from app.services.packets import synthetic

    X, y = training_rows(seeds or synthetic.TRAIN_SEEDS)
    clf = LogisticRegression(C=1.0, solver="liblinear", max_iter=1000)
    clf.fit(X, y)
    return {"intercept": round(float(clf.intercept_[0]), 6),
            "coef": {name: round(float(w), 6) for name, w in zip(ft.FEATURES, clf.coef_[0])},
            "rows": len(y), "positives": int(sum(y))}


def write(result: dict, stats: dict) -> None:
    text = MODEL_FILE.read_text(encoding="utf-8")
    block = (
        "# --- fitted: begin (generated by scripts/fit_packet_boundaries.py) ---\n"
        f'MODEL_VERSION = "{VERSION}"\n'
        f"INTERCEPT = {result['intercept']!r}\n"
        "COEF: dict[str, float] = {\n"
        + "".join(f'    "{k}": {w!r},\n' for k, w in result["coef"].items())
        + "}\n"
        f"FIT_STATS: dict[str, float] = {json.dumps(stats, sort_keys=True)}\n"
        "# --- fitted: end ---"
    )
    new = re.sub(r"# --- fitted: begin.*?# --- fitted: end ---", lambda _m: block, text, flags=re.S)
    MODEL_FILE.write_text(new, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    result = fit()
    if args.write:
        write(result, {"rows": result["rows"], "positives": result["positives"]})
        import importlib

        from app.services.packets import model, planner, synthetic

        importlib.reload(model)
        importlib.reload(planner)
        held = planner.evaluate(synthetic.corpus(synthetic.HELD_OUT_SEEDS))
        write(result, {"rows": result["rows"], "positives": result["positives"],
                       "held_out_precision": held["precision"], "held_out_recall": held["recall"]})
        print(json.dumps({"fit": result, "held_out": held}, indent=2))
    else:
        print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
