"""ARCH43-S1:model — the logistic boundary model, scored with plain math.

The coefficients below are FITTED, not hand-set: scikit-learn's
LogisticRegression on the labelled synthetic packets (synthetic.TRAIN_SEEDS)
by `python scripts/fit_packet_boundaries.py --write`, which rewrites the block
between the markers. verify_arch43 T4 refits and checks the shipped numbers
reproduce, and measures precision/recall on held-out packets.

Scoring needs no scikit-learn at runtime (the LIGHT worker profile imports
no model libraries): p = 1 / (1 + exp(-(b + w . x))).
"""

from __future__ import annotations

import math
from typing import Mapping, Sequence

from app.services.packets.features import FEATURES

# --- fitted: begin (generated by scripts/fit_packet_boundaries.py) ---
MODEL_VERSION = "pb-1"
INTERCEPT = -3.704565
COEF: dict[str, float] = {
    "layout_change": 2.796494,
    "page_one": 5.452208,
    "continues": -4.794162,
    "prev_last": 5.072901,
    "prev_blank": 0.236898,
    "blank": 0.0,
    "separator": 3.372166,
    "type_change": 0.826542,
    "title": 1.043692,
    "number_change": 0.915124,
    "number_same": -3.430563,
    "text_jump": 1.931622,
}
FIT_STATS: dict[str, float] = {"held_out_precision": 0.9754, "held_out_recall": 0.8982, "positives": 2976, "rows": 6309}
# --- fitted: end ---


def probability(features: Mapping[str, float]) -> float:
    z = INTERCEPT + sum(COEF[name] * float(features[name]) for name in FEATURES)
    if z >= 0:
        return 1.0 / (1.0 + math.exp(-z))
    e = math.exp(z)
    return e / (1.0 + e)


def probabilities(pair_features: Sequence) -> list[float]:
    """Boundary probability before each page; page 1 always starts a document."""
    return [1.0 if f is None else probability(f) for f in pair_features]


__all__ = ["COEF", "FIT_STATS", "INTERCEPT", "MODEL_VERSION", "probabilities", "probability"]
