"""add email settings

Revision ID: 08cbbe53034b
Revises: 188ffda2ce99
Create Date: 2026-07-14 09:19:41.033759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cbbe53034b'
down_revision: Union[str, None] = '188ffda2ce99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=512), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('encryption', sa.Enum('NONE', 'TLS', 'SSL', name='emailencryption'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_settings_is_enabled'), 'email_settings', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_email_settings_user_id'), 'email_settings', ['user_id'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_settings_user_id'), table_name='email_settings')
    op.drop_index(op.f('ix_email_settings_is_enabled'), table_name='email_settings')
    op.drop_table('email_settings')
    # ### end Alembic commands ###