"""document_settings_timestamp_columns

Revision ID: 1f85effe07bb
Revises: d205162021ef
Create Date: 2026-07-28 13:08:19.251021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f85effe07bb'
down_revision: Union[str, None] = 'd205162021ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_settings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_settings', 'updated_at')
    op.drop_column('document_settings', 'created_at')
    # ### end Alembic commands ###
