"""arch01_align_enum_names_and_indexes

ARCH-01 Stabilization — corrective alignment of the PostgreSQL schema with the
model layer as corrected in Phase 2.

Not part of Expand -> Migrate -> Contract. Those legs exist to evolve a schema
across a rolling deployment; this reconciles a schema with models that were
already changed. Atomic, reversible, no data movement.

Three operation groups:

  A. Six enum type renames. Snake_case names were added to the models after
     their original migrations were written, so the database retained the
     names SQLAlchemy derived from the Python class (AIProvider -> aiprovider,
     EmailEncryption -> emailencryption). All six have byte-identical value
     sets, so ALTER TYPE ... RENAME TO is the complete fix: a catalog
     operation, transactional, no table rewrite.

  B. Rebuild of the ai_provider type. This one is NOT a rename. The Python
     enum was narrowed from four providers to two, and Alembic compares enum
     types by compiled DDL name rather than by value set — so a rename alone
     would silence the diff while the database still held OPENAI and CLAUDE.
     That is drift Alembic structurally cannot detect. With ai_settings empty,
     the type is rebuilt with the two values it should have.

  C. Three stale index drops. Low-cardinality B-trees that the planner ignores
     while every write pays for them. ix_work_items_file_type is superseded in
     ARCH-02 by the composite (workspace_id, file_type).

Hand-written because the autogenerated equivalent cannot execute: every
alter_column(type_=sa.Enum(...)) it produced would fail with "cannot be
automatically cast", since PostgreSQL requires an explicit USING clause between
enum types and autogenerate emits none.

Deliberately NOT touched: the unique index ix_work_items_stored_filename, which
guarantees two uploads cannot collide on the same filesystem key. Autogenerate
proposed dropping it in a form visually identical to the three harmless drops
above; the Phase 2 model correction removed it from the diff entirely.

Revision ID: 74a07cbe5d7e
Revises: e66f8636c46a
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '74a07cbe5d7e'
down_revision: Union[str, None] = 'e66f8636c46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ===========================================================================
# Group A — enum types renamed in place
#
# (current_name, target_name). Value sets are identical on both sides of every
# pair, verified against the Phase 2 drift report, so no cast is required.
# ===========================================================================

ENUM_RENAMES: tuple[tuple[str, str], ...] = (
    ("logic_operator_enum", "logic_operator"),
    ("emailencryption", "email_encryption"),
    ("notificationtype", "notification_type"),
    ("notificationpriority", "notification_priority"),
    ("notificationchannel", "notification_channel"),
    ("notificationstatus", "notification_status"),
)

# ===========================================================================
# Group B — ai_provider rebuild
# ===========================================================================

AI_PROVIDER_LEGACY_NAME = "aiprovider"
AI_PROVIDER_TARGET_NAME = "ai_provider"
AI_PROVIDER_LEGACY_VALUES = ("GROQ", "GEMINI", "OPENAI", "CLAUDE")
AI_PROVIDER_TARGET_VALUES = ("GROQ", "GEMINI")

# ===========================================================================
# Group C — stale indexes
#
# (index_name, table_name, columns, unique)
# ===========================================================================

STALE_INDEXES: tuple[tuple[str, str, list[str], bool], ...] = (
    ("ix_users_is_active", "users", ["is_active"], False),
    ("ix_users_is_superuser", "users", ["is_superuser"], False),
    ("ix_work_items_file_type", "work_items", ["file_type"], False),
)


# ===========================================================================
# Helpers
# ===========================================================================

def _type_exists(bind, type_name: str) -> bool:
    """Returns True if a PostgreSQL type of the given name exists."""
    return (
        bind.execute(
            sa.text("SELECT 1 FROM pg_type WHERE typname = :name"),
            {"name": type_name},
        ).fetchone()
        is not None
    )


def _index_exists(bind, index_name: str) -> bool:
    """Returns True if an index of the given name exists."""
    return (
        bind.execute(
            sa.text("SELECT 1 FROM pg_class WHERE relname = :name AND relkind = 'i'"),
            {"name": index_name},
        ).fetchone()
        is not None
    )


def _rename_type(bind, current_name: str, target_name: str) -> None:
    """
    Renames a PostgreSQL type, tolerating a prior partial run.

    Skips silently when the rename has already been applied, so re-running the
    migration converges rather than failing on the first completed pair.
    """
    if not _type_exists(bind, current_name):
        if _type_exists(bind, target_name):
            return  # Already renamed by an earlier partial run.
        raise RuntimeError(
            f"Type '{current_name}' not found and '{target_name}' does not "
            "exist either. The schema is not in the state this migration "
            "expects; investigate before proceeding."
        )

    if _type_exists(bind, target_name):
        raise RuntimeError(
            f"Cannot rename '{current_name}' to '{target_name}': the target "
            "name is already taken by a different type."
        )

    op.execute(f'ALTER TYPE "{current_name}" RENAME TO "{target_name}"')


def _assert_ai_settings_ready(bind) -> None:
    """
    Verifies the ai_provider rebuild is safe before any type is created.

    Two conditions. A server-side default would block the column's type change
    with "default for column cannot be cast automatically", and any row holding
    a removed provider would be silently at risk. Alembic wraps this revision
    in a transaction, so raising here leaves the database untouched.
    """
    column_default = bind.execute(
        sa.text(
            """
            SELECT column_default
            FROM information_schema.columns
            WHERE table_name = 'ai_settings' AND column_name = 'provider'
            """
        )
    ).scalar()

    if column_default is not None:
        raise RuntimeError(
            "ai_settings.provider carries a server-side default "
            f"({column_default!r}). The type change would fail. Drop and "
            "restore the default explicitly before running this migration."
        )

    removed_values = tuple(
        set(AI_PROVIDER_LEGACY_VALUES) - set(AI_PROVIDER_TARGET_VALUES)
    )
    orphaned = bind.execute(
        sa.text(
            """
            SELECT count(*) FROM ai_settings
            WHERE provider::text = ANY(:removed)
            """
        ),
        {"removed": list(removed_values)},
    ).scalar_one()

    if orphaned:
        raise RuntimeError(
            f"{orphaned} ai_settings row(s) reference a provider being "
            f"removed ({', '.join(sorted(removed_values))}). Remap or delete "
            "them before running this migration."
        )


def _quoted(values: tuple[str, ...]) -> str:
    """Renders enum values as a quoted, comma-separated SQL list."""
    return ", ".join(f"'{value}'" for value in values)


# ===========================================================================
# Upgrade
# ===========================================================================

def upgrade() -> None:
    bind = op.get_bind()

    # --- Group A: rename six enum types ------------------------------------
    for current_name, target_name in ENUM_RENAMES:
        _rename_type(bind, current_name, target_name)

    # --- Group B: rebuild ai_provider with the narrowed value set ----------
    if _type_exists(bind, AI_PROVIDER_LEGACY_NAME):
        _assert_ai_settings_ready(bind)

        op.execute(
            f"CREATE TYPE {AI_PROVIDER_TARGET_NAME} AS ENUM "
            f"({_quoted(AI_PROVIDER_TARGET_VALUES)})"
        )

        # The explicit cast fails loudly on any out-of-range value rather than
        # discarding it. The assertion above already guarantees none exist;
        # this keeps the migration safe if it is ever replayed elsewhere.
        op.execute(
            "ALTER TABLE ai_settings "
            f"ALTER COLUMN provider TYPE {AI_PROVIDER_TARGET_NAME} "
            f"USING provider::text::{AI_PROVIDER_TARGET_NAME}"
        )

        op.execute(f"DROP TYPE {AI_PROVIDER_LEGACY_NAME}")

    # --- Group C: drop stale indexes ---------------------------------------
    for index_name, table_name, _columns, _unique in STALE_INDEXES:
        if _index_exists(bind, index_name):
            op.drop_index(index_name, table_name=table_name)


# ===========================================================================
# Downgrade
# ===========================================================================

def downgrade() -> None:
    """
    Restores the legacy type names, the four-value provider enum, and the three
    indexes.

    Fully reversible. No data is lost in either direction: the upgrade refuses
    to run while any row holds a provider value being removed, so the reverse
    cast cannot encounter one either.
    """
    bind = op.get_bind()

    # --- Group C: recreate stale indexes -----------------------------------
    for index_name, table_name, columns, unique in reversed(STALE_INDEXES):
        if not _index_exists(bind, index_name):
            op.create_index(index_name, table_name, columns, unique=unique)

    # --- Group B: restore the four-value provider enum ---------------------
    if _type_exists(bind, AI_PROVIDER_TARGET_NAME):
        op.execute(
            f"CREATE TYPE {AI_PROVIDER_LEGACY_NAME} AS ENUM "
            f"({_quoted(AI_PROVIDER_LEGACY_VALUES)})"
        )
        op.execute(
            "ALTER TABLE ai_settings "
            f"ALTER COLUMN provider TYPE {AI_PROVIDER_LEGACY_NAME} "
            f"USING provider::text::{AI_PROVIDER_LEGACY_NAME}"
        )
        op.execute(f"DROP TYPE {AI_PROVIDER_TARGET_NAME}")

    # --- Group A: restore legacy type names --------------------------------
    for current_name, target_name in reversed(ENUM_RENAMES):
        _rename_type(bind, target_name, current_name)
