"""add token pricing to ai_settings

Revision ID: 8c5d9ab2c4b1
Revises: e30fd419c4f7
Create Date: 2026-07-23 10:38:03.692495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5d9ab2c4b1'
down_revision: Union[str, None] = 'e30fd419c4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_settings",
        sa.Column("input_cost_per_1k_tokens", sa.Float(), nullable=False, server_default="0.0"),
    )

    op.add_column(
        "ai_settings",
        sa.Column("output_cost_per_1k_tokens", sa.Float(), nullable=False, server_default="0.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_settings', 'output_cost_per_1k_tokens')
    op.drop_column('ai_settings', 'input_cost_per_1k_tokens')
    # ### end Alembic commands ###