"""add token_usage to conversation_messages

Revision ID: 90ffbe0abfea
Revises: 08cbbe53034b
Create Date: 2026-07-20 15:33:46.614971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ffbe0abfea'
down_revision: Union[str, None] = '08cbbe53034b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('token_usage', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'token_usage')
    # ### end Alembic commands ###