"""add_workspace_table

Revision ID: c9ff552177bf
Revises: 90ffbe0abfea
Create Date: 2026-07-20 17:52:45.089526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ff552177bf'
down_revision: Union[str, None] = '90ffbe0abfea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_is_active'), 'workspaces', ['is_active'], unique=False)
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_is_active'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###