"""F-045: the web, worker and enrich images install requirements-web.txt, not everything.

Every image used to install the full requirements.txt, so the API image carried
the OCR engine (PaddleOCR, PaddleX, OpenCV: about 1.2 GB), a test mocking
library and an unused Kubernetes client. The per-image files are generated by
scripts/image_requirements.py; these tests prove they match requirements.txt,
that the Dockerfile uses them, and that the API and the light and enrich
workers start with nothing outside the web set importable.
"""

from __future__ import annotations

import importlib.metadata
import importlib.util
import re
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parents[2]


def _full_environment() -> bool:
    try:
        importlib.metadata.distribution("paddleocr")
    except importlib.metadata.PackageNotFoundError:
        return False
    return True


# The files are derived from the graph of everything in requirements.txt, so these run where
# development and CI install all of it, not inside an image built from requirements-web.txt.
pytestmark = pytest.mark.skipif(not _full_environment(), reason="needs the full requirements.txt installed")


def _load_tool():
    spec = importlib.util.spec_from_file_location("image_requirements", BACKEND / "scripts" / "image_requirements.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _names(path: Path) -> set[str]:
    return {re.split(r"[=\[]", line)[0].strip().lower().replace("_", "-")
            for line in path.read_text(encoding="utf-8").splitlines() if line and not line.startswith("#")}


def test_the_image_files_are_generated_from_requirements_txt():
    web_text, ocr_text = _load_tool().compute()
    assert (BACKEND / "requirements-web.txt").read_text(encoding="utf-8") == web_text, \
        "requirements-web.txt is stale: run python scripts/image_requirements.py"
    assert (BACKEND / "requirements-ocr.txt").read_text(encoding="utf-8") == ocr_text, \
        "requirements-ocr.txt is stale: run python scripts/image_requirements.py"


def test_the_web_set_has_no_ocr_engine_or_dev_tools_but_keeps_what_the_api_uses():
    web = _names(BACKEND / "requirements-web.txt")
    ocr = _names(BACKEND / "requirements-ocr.txt")
    assert not web & {"paddlepaddle", "paddleocr", "paddlex", "opencv-contrib-python", "modelscope",
                      "moto", "pytest", "pytest-env", "kubernetes"}
    assert {"paddlepaddle", "paddleocr", "paddlex", "opencv-contrib-python"} <= ocr
    # The API renders PDFs, stores files in S3/R2 and embeds search queries itself.
    assert {"pypdfium2", "boto3", "sentence-transformers", "torch", "fastapi", "uvicorn", "gunicorn"} <= web
    assert not web & ocr


def test_the_dockerfile_installs_the_web_set_and_adds_ocr_only_to_the_ocr_target():
    dockerfile = (BACKEND / "Dockerfile").read_text(encoding="utf-8")
    stages = re.split(r"^FROM ", dockerfile, flags=re.MULTILINE)[1:]
    by_name = {stage.split()[2]: stage for stage in stages}
    assert "pip install --no-cache-dir -r requirements-web.txt" in by_name["base"]
    assert "-r requirements.txt" not in dockerfile
    for name in ("web", "worker", "enrich"):
        assert by_name[name].startswith("base AS"), name
        assert "requirements-ocr.txt" not in by_name[name], name
    assert "pip install --no-cache-dir -r requirements-ocr.txt" in by_name["ocr"]


IMPORT_CHECK = textwrap.dedent(
    """
    import importlib, importlib.abc, importlib.metadata as md, pkgutil, re, sys
    from pathlib import Path

    def names(path):
        return {re.split(r"[=\\[]", l)[0].strip().lower().replace("_", "-")
                for l in Path(path).read_text().splitlines() if l and not l.startswith("#")}

    web = names("requirements-web.txt")
    pinned = names("requirements.txt")
    blocked = set()
    for module, dists in md.packages_distributions().items():
        dists = {d.lower().replace("_", "-") for d in dists}
        if dists & pinned and not dists & web:
            blocked.add(module)

    class Block(importlib.abc.MetaPathFinder):
        def find_spec(self, name, path=None, target=None):
            if name.split(".")[0] in blocked:
                raise ModuleNotFoundError(f"{name} is not in requirements-web.txt", name=name)
            return None

    sys.meta_path.insert(0, Block())
    assert {"paddle", "paddleocr", "paddlex", "cv2", "moto", "kubernetes"} <= blocked, sorted(blocked)
    try:
        import paddleocr  # noqa: F401
    except ModuleNotFoundError:
        pass
    else:
        raise AssertionError("the import blocker does not block paddleocr")

    if sys.argv[1] != "modules":  # a worker's start-up check, in a fresh process like the real one
        from app.workers.profiles import assert_imports_match_profile, get_profile
        from app.workers.handlers import register_all
        register_all()
        assert_imports_match_profile(get_profile(sys.argv[1]))
        print("OK", sys.argv[1])
        sys.exit(0)

    import app.main  # the API, with every router registered
    assert app.main.app.routes

    # Every module the web, worker and enrich images can load, except the OCR engine's own.
    OCR_ONLY = {"app.services.ocr.paddle", "app.services.ocr_service"}
    failed = []
    import app
    for info in pkgutil.walk_packages(app.__path__, "app."):
        if info.name in OCR_ONLY or info.name.startswith("app.reranker"):
            continue
        try:
            importlib.import_module(info.name)
        except ModuleNotFoundError as exc:
            if exc.name and exc.name.split(".")[0] in blocked:
                failed.append(f"{info.name}: {exc}")
    assert not failed, failed
    print("OK", len(blocked), "modules blocked")
    """
)


@pytest.mark.parametrize("what", ["modules", "light", "enrich"])
def test_the_api_and_the_light_and_enrich_workers_start_with_only_the_web_set(what):
    result = subprocess.run([sys.executable, "-c", IMPORT_CHECK, what], cwd=BACKEND, capture_output=True,
                            text=True, timeout=600, env={**__import__("os").environ, "PYTHONPATH": str(BACKEND)})
    assert result.returncode == 0, result.stderr[-3000:]
    assert result.stdout.strip().splitlines()[-1].startswith("OK"), result.stdout[-500:]
