"""
FlowPilot AI Prompt Package
"""

PROMPT_PACKAGE_VERSION = "1.0.0"

CLASSIFICATION_PROMPT_VERSION = "1.0.0"

ENTITY_EXTRACTION_PROMPT_VERSION = "1.0.0"

SUMMARY_PROMPT_VERSION = "1.0.0"

RAG_PROMPT_VERSION = "1.1.0"