#!/usr/bin/env python3
"""Write docs/CONFIGURATION.md: every backend setting, its type, default and notes.

    python docs/hardening/tools/config_reference.py

F-011: ~230 of the ~300 settings in backend/app/core/config.py were in no
template, so an operator could not see what they are or what the code uses
when they are unset. This lists every one, read from the code with `ast` (so
the reference cannot drift from it), with the comment written above it, and
says whether each appears in .env.example / .env.production.template and
whether the production start-up guard checks it.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BACKEND = ROOT / "backend"
CONFIG = BACKEND / "app" / "core" / "config.py"
GUARD = BACKEND / "app" / "core" / "production_guard.py"
OUT = ROOT / "docs" / "CONFIGURATION.md"


def _env_keys(path: Path) -> set[str]:
    keys: set[str] = set()
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r"\s*#?\s*([A-Z][A-Z0-9_]+)\s*=", line)
        if match:
            keys.add(match.group(1))
    return keys


def _comment_above(lines: list[str], lineno: int) -> str:
    """The `#` comment block directly above line `lineno` (1-based), joined."""
    out: list[str] = []
    index = lineno - 2
    while index >= 0 and lines[index].strip().startswith("#"):
        out.append(lines[index].strip().lstrip("#").strip())
        index -= 1
    text = " ".join(reversed([part for part in out if part]))
    return text.replace("|", "\\|")


def _cell(text: str, limit: int) -> str:
    text = " ".join(text.split()).replace("|", "\\|")
    return text if len(text) <= limit else text[: limit - 1] + "…"


def main() -> None:
    source = CONFIG.read_text(encoding="utf-8-sig")
    lines = source.splitlines()
    tree = ast.parse(source)
    example = _env_keys(BACKEND / ".env.example")
    production = _env_keys(BACKEND / ".env.production.template")
    guarded = set(re.findall(r"\b([A-Z][A-Z0-9_]{3,})\b", GUARD.read_text(encoding="utf-8"))) if GUARD.exists() else set()

    rows: list[str] = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.ClassDef) and node.name == "Settings"):
            continue
        for item in node.body:
            if not (isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name)):
                continue
            name = item.target.id
            if not name.isupper():
                continue
            kind = _cell(ast.unparse(item.annotation), 40)
            default = "required" if item.value is None else _cell(ast.unparse(item.value), 60)
            where = ", ".join(
                label
                for label, present in (("example", name in example), ("production", name in production),
                                       ("guard", name in guarded))
                if present
            ) or "—"
            note = _cell(_comment_above(lines, item.lineno), 220)
            rows.append(f"| `{name}` | `{kind}` | `{default}` | {where} | {note} |")

    header = [
        "# Backend configuration reference",
        "",
        "_Generated by `docs/hardening/tools/config_reference.py` from `backend/app/core/config.py`; do not",
        "edit by hand. Re-run it after changing a setting._",
        "",
        "Every setting can be set as an environment variable of the same name (or in `backend/.env`).",
        "**Unset, the default below applies.** In production and staging the start-up guard",
        "(`app/core/production_guard.py`) refuses to start on unsafe values of the settings marked",
        "`guard`, and lists every problem by name. The production compose file passes on every variable",
        "that `.env.production.template` asks for (F-047); a setting outside the template keeps its default",
        "in the containers unless you add it to the service's `environment:` in `docker-compose.prod.yml`.",
        "",
        f"{len(rows)} settings. Columns: name, type, default, where it appears (`example` =",
        "`.env.example`, `production` = `.env.production.template`, `guard` = checked by the production",
        "guard), and the comment written above it in the code.",
        "",
        "| Setting | Type | Default | In | Notes |",
        "|---|---|---|---|---|",
    ]
    OUT.write_text("\n".join(header + rows) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(rows)} settings")


if __name__ == "__main__":
    main()
